/*
 * Copyright 2008-2010 The Zoocen Development Team
 *
 * This file is part of Zoocen.
 *
 * Zoocen is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * Zoocen is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Zoocen; if not, write to the Free Software Foundation, Inc., 51 Franklin St,
 * Fifth Floor, Boston, MA 02110-1301 USA
 */
package graphics.configuration;

import graphics.SpecieData;
import graphics.MainWindow;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Hashtable;
import java.util.List;
import zoocen.Cell;
import zoocen.specie;

/**
 *
 * @author  sandra
 */
public class AddCellFrame extends javax.swing.JFrame implements ActionListener{
    //ChooseParametersPanel cCellPanel;
    SetCellPanel setCell;
    TableCellPanel tCellPanel;
    List<SpecieData> SData;
    Hashtable<String, SpecieData> NewSData;
    MainWindow mainWindow;
    
    /** Creates new form AddCellFrame */
    public AddCellFrame(MainWindow mainWindow) {               
        initComponents();
        this.setSize(800, 491);
        //this.cCellPanel = new ChooseParametersPanel();
        this.setCell = new SetCellPanel();
        this.setCell.jButtonSet.addActionListener(this);
        this.tCellPanel= new TableCellPanel();
        this.jTabbedPane1.addTab("Choose Cell", this.setCell);
        //this.jTabbedPane1.addTab("New Cell", cCellPanel);
        //this.jTabbedPane1.addTab("Cells created", tCellPanel);
       // cCellPanel.setVisible(true);
        this.mainWindow = mainWindow;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButtonWriteConfiguration = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        jButtonWriteConfiguration.setText("Write Configuration");
        jButtonWriteConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteConfigurationActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonWriteConfiguration);

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonClose);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(463, 463, 463)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
            this.setVisible(false);
}//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonWriteConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteConfigurationActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonWriteConfigurationActionPerformed
    
    public void setSpecieCombo(List<SpecieData> SData){    	
    	this.SData = SData;
        //this.mainWindow.World.cells
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonWriteConfiguration;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public void actionPerformed(ActionEvent arg0) {
        if(arg0.getSource() == this.setCell.jButtonSet){
            String cellName = this.setCell.getCell();          
            int CellIndex = Integer.valueOf(cellName.substring(cellName.indexOf(" ") + 1));
            CellIndex--;
            Cell cell = new Cell(CellIndex);            
            for(int i = 0; i < this.SData.size(); i++){        
                SpecieData data = this.SData.get(i);
                cell.addSpecie(new specie(data.ID, data.Name, data.growing_Rate));
            }            
            ChooseParametersPanel cCellPanel = new ChooseParametersPanel(cell);
            cCellPanel.setVisible(true);
            for(int i = 0; i < this.jTabbedPane1.getTabCount(); i++){
                if(this.jTabbedPane1.getTitleAt(i).matches(cellName)){
                    this.jTabbedPane1.removeTabAt(i);       
                }
            }
            this.jTabbedPane1.addTab(cellName, cCellPanel); 
            
            this.jTabbedPane1.setSelectedIndex(this.jTabbedPane1.getTabCount()-1);
            this.mainWindow.setCell(cell);
            this.mainWindow.setPanelCell(CellIndex);
        }
    }
    
}
